# Generated by Django 3.1.2 on 2020-10-03 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100)),
                ('long_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webauth.tool')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webauth.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='useraccess',
            constraint=models.UniqueConstraint(fields=('user_id', 'tool_id'), name='unique_access'),
        ),
    ]
